window.data = {
    login: "omarahmed30",
    id: 26211014,
    avatar_url: "https://avatars1.githubusercontent.com/u/26211014?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/omarahmed30",
    html_url: "https://github.com/omarahmed30",
    followers_url: "https://api.github.com/users/omarahmed30/followers",
    following_url: "https://api.github.com/users/omarahmed30/following{/other_user}",
    gists_url: "https://api.github.com/users/omarahmed30/gists{/gist_id}",
    starred_url: "https://api.github.com/users/omarahmed30/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/omarahmed30/subscriptions",
    organizations_url: "https://api.github.com/users/omarahmed30/orgs",
    repos_url: "https://api.github.com/users/omarahmed30/repos",
    events_url: "https://api.github.com/users/omarahmed30/events{/privacy}",
    received_events_url: "https://api.github.com/users/omarahmed30/received_events",
    type: "User",
    site_admin: false,
    name: "Omar Ahmed",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: true,
    bio: null,
    public_repos: 20,
    public_gists: 0,
    followers: 4,
    following: 0,
    created_at: "2017-03-06T01:55:44Z",
    updated_at: "2018-03-26T02:04:18Z"
    }